apiVersion: v1
clusters:
- cluster:
    certificate-authority-data: ==base64-encoded-cert==
    server: https://robrich.snip.westus2.azmk8s.io:443
  name: robrich
contexts:
- context:
    cluster:  robrich
    user:  clusterUser_kubernetes_robrich
  name:  robrich
current-context:  robrich
kind: Config
preferences: {}
users:
- name:  clusterUser_kubernetes_robrich
  user:
    client-certificate-data: ==base64-encoded-cert==
    client-key-data: ==base64-encoded-key==
    token: ==some-random-bits==