name: Docker Buid and Push, Kubernetes run

on:
  push:
    branches: 
      - "main"
  workflow_dispatch: 
  
jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    
    - name: Docker Login
      uses: docker/login-action@v3.1.0
      with:
        registry: ${{ secrets.ACR_URL }}
        username: ${{ secrets.ACR_USERNAME }}
        password: ${{ secrets.ACR_PASSWORD }}
        logout: true

    - name: Kubernetes Set Context
      uses: Azure/k8s-set-context@v3.0
      with:
        method: kubeconfig
        # Contents of kubeconfig file
        kubeconfig: ${{ secrets.KUBE_CONFIG }}
    
    - name: Build build & push, Kubectl apply
      env:
        DOCKER_BUILDKIT: 1
      run: |
        docker build -t ${{ secrets.ACR_URL }}/levelupdevops:${{ github.sha }} .
        # docker push ${{ secrets.ACR_URL }}/levelupdevops:${{ github.sha }}
        docker push https://hub.docker.com/repository/docker/khoapham1983/demo:${{ github.sha }}
        sed -i'' -e 's/ACR_URL/${{ secrets.ACR_URL }}/g' -e 's/AKS_URL/${{ secrets.AKS_URL }}/g' -e 's/IMAGE_LABEL/${{ github.sha }}/g' k8s.yaml
        kubectl apply -f k8s.yaml
